posts/blueprint.py
from flask import Blueprint, redirect, url_for, render_template, request
from models import *
from forms import *
from app import db, app
from flask_security import login_required
from flask_uploads import UploadSet, configure_uploads, IMAGES
from PIL import Image
import os

posts = Blueprint('posts', __name__, template_folder='templates')

# Загрузка файлов

photos = UploadSet('photos', IMAGES)
configure_uploads(app, photos)


# создание поста
@posts.route('/create', methods=['POST', 'GET'])
@login_required
def create_post():
    if request.method == 'POST':
        title = request.form['title']
        body = request.form['body']
        image = photos.save(request.files['image'])

        try:
            post = Post(title=title, body=body, image=image)
            db.session.add(post)
            db.session.commit()
        except:
            print('база не смогла')
        return redirect(url_for('posts.index'))

    form = PostForm()
    return render_template('posts/create_post.html', form=form)

#Изменение поста
@posts.route('/<slug>/edit/', methods=['POST', 'GET'])
@login_required
def edit_post(slug):
    post = Post.query.filter(Post.slug == slug).first_or_404()
    if request.method == 'POST':
        form = PostForm(formdata=request.form, obj=post)
        form.populate_obj(post)
        db.session.commit()

        return redirect(url_for('posts.post_detail', slug=post.slug))

    form = PostForm(obj=post)
    return render_template('posts/edit_post.html', post=post, form=form)

# Изменение категории
@posts.route('/<slug>/tagedit/', methods=['POST', 'GET'])
@login_required
def edit_tag(slug):
    tag = Tag.query.filter(Tag.slug == slug).first_or_404()
    if request.method == 'POST':
        form = TagForm(formdata=request.form, obj=tag)
        form.populate_obj(tag)
        db.session.commit()

        return redirect(url_for('posts.tag_detail', slug=tag.slug))

    form = TagForm(obj=tag)
    return render_template('posts/edit_tag.html', tag=tag, form=form)

#Изменение слайда
@posts.route('/<id>/slideedit/', methods=['POST', 'GET'])
@login_required
def edit_slide(id):
    slide = Slider.query.filter(Slider.id == id).first_or_404()
    if request.method == 'POST':
        form = SliderForm(formdata=request.form, obj=slide)
        form.populate_obj(slide)
        db.session.commit()

        return redirect(url_for('adm', id=slide.id))

    form = SliderForm(obj=slide)
    return render_template('posts/edit_slide.html', slide=slide, form=form)

# Удаление через админку по id
@posts.route('/<id>/delete/', methods=['POST', 'GET'])
@login_required
def delete(*args, **kwargs):
    type = request.args.get('type')
    id = list(request.view_args.values())[0]
    if type == 'post':
        try:
            post = Post.query.filter(Post.id == id).first_or_404()
            db.session.delete(post)
            db.session.commit()
            os.remove("static/image/"+post.image)
        except:
            print('база не спогла')
        return redirect(url_for('adm'))
    if type == 'tag':
        try:
            tag = Tag.query.filter(Tag.id == id).first_or_404()
            db.session.delete(tag)
            db.session.commit()
            os.remove("static/image/"+tag.image)
            os.remove("static/image/tagimage/"+tag.image)
        except:
            print('база не спогла')
        return redirect(url_for('adm'))
    if type == 'slide':
        try:
            slide = Slider.query.filter(Slider.id == id).first_or_404()
            db.session.delete(slide)
            db.session.commit()
            os.remove("static/image/"+slide.image)
            os.remove("static/image/slider/"+slide.image)
        except:
            print('база не спогла')
        return redirect(url_for('adm'))

    return render_template('adm.html')

# Главная страница каталога, Поиск и Пагинация
@posts.route('/')
def index(*args, **kwargs):
    q = request.args.get('q')
    page = request.args.get('page')
    s = request.args.get('slug')
    tags = Tag.query.all()


    if page and page.isdigit():
        page = int(page)
    else:
        page = 1

    if q:
        posts = Post.query.filter(Post.title.contains(q) | Post.body.contains(q))  # .all()
    else:
        posts = Post.query.order_by(Post.created.desc())

    if s:
        tag = Tag.query.filter(Tag.slug == s).first_or_404()
        posts = tag.posts

    pages = posts.paginate(page=page, per_page=6)


    return render_template('posts/index.html', posts=posts, pages=pages, tags=tags,)

# Страница товара
@posts.route('/<slug>')
def post_detail(slug):
    post = Post.query.filter(Post.slug == slug).first_or_404()
    tags = post.tags
    img = Image.open("static/image/"+post.image)
    if img.size[0] != '450':
        image = img.resize((450, 450), Image.ANTIALIAS)
    image = image.save("static/image/"+post.image)

    return render_template('posts/post_detail.html', post=post, tags=tags, image=image)

# Странца с товарами отсортированными по категории
@posts.route('/tag/<slug>')
def tag_detail(slug):
    tag = Tag.query.filter(Tag.slug == slug).first_or_404()
    posts = tag.posts.all()

    return render_template('posts/tag_detail.html', tag=tag, posts=posts)

templates/about.html
{% extends 'base.html' %}

{% block content %}
<h2>kekw</h2>
{% endblock%}

templates/adm.html
{% extends 'base.html' %}

{% block title %}
  Админка
{% endblock %}

{% block content_title %}
  Управление содержимым
{% endblock %}

{% block content %}

<!--Блок отобрадения кнопок добавления товаров, категорий и слайдов-->

<div style="display:flex; justify-content:space-around; margin:50px 0 50px 0;">
  <form action="{{url_for('adm')}}" method="get">
    <input type="submit" class="btn btn-outline-primary" name="create" value="Создать товар">
  </form>
  <form action="{{url_for('adm')}}" method="get">
    <input type="submit" class="btn btn-outline-primary" name="create" value="Создать категорию">
  </form>
  <form action="{{url_for('adm') }}" method="get">
    <input type="submit" class="btn btn-outline-primary" name="create" value="Создать слайд">
  </form>
</div>

<!--блок отображения списка товаров, категорий и слайдов-->

<div class="row">
  <div class="col-md-4">
    <h5>Товары</h5>
    {% for p in posts %}
      <div class="">
        <a type="button" class="btn btn-outline-secondary" href="{{url_for('posts.post_detail', slug=p.slug)}}">{{p.title}}</a>
        <a type="button" class="btn btn-outline-success" href="{{url_for('posts.edit_post', slug=p.slug)}}">Edit</a>
        <a type="button" class="btn btn-outline-danger" name="delpost" href="{{url_for('posts.delete', id=p.id, type='post')}}">Del</a>
      </div>
    {% endfor %}
  </div>

  <div class="col-md-4">
    <h5>Категории</h5>
    {% for t in tags %}
      <div class="">
        <a type="button" class="btn btn-outline-secondary" href="{{url_for('posts.tag_detail', slug=t.slug)}}">{{t.name}}</a>
        <a type="button" class="btn btn-outline-success" href="{{url_for('posts.edit_tag', slug=t.slug)}}">Edit</a>
        <a type="button" class="btn btn-outline-danger" name="delcategory" href="{{url_for('posts.delete', id=t.id, type='tag')}}">Del</a>
      </div>
    {% endfor %}
  </div>

  <div class="col-md-4">
    <h5>Слайды</h5>
    {% for s in slides %}
      <div class="">
        <a type="button" class="btn btn-outline-secondary" href="#">{{s.title}}</a>
        <a type="button" class="btn btn-outline-success" href="{{url_for('posts.edit_slide', id=s.id)}}">Edit</a>
        <a type="button" class="btn btn-outline-danger" name="delslide" href="{{url_for('posts.delete', id=s.id, type='slide')}}">Del</a>
      </div>
    {% endfor %}
  </div>
</div>


{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>

        {% block title %}

        {% endblock %}

    </title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">

</head>

<body>
<main class="flex-shrink-0">

    <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark ">
        <div class="container" id="top_nav">
            <a class="navbar-brand" href=" {{ url_for('index') }}">Главная</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

            <div class="collapse navbar-collapse " id="navbarCollapse">
                <ul class="navbar-nav me-auto mb-2 mb-md-0">

                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{{ url_for('posts.index') }}">Каталог</a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{{url_for('where')}}">Где куппить</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{{url_for('about')}}">О заводе</a>
                    </li>

                    <li class="nav-item">
                        {% if current_user.has_role('admin') %}
                        <a class="nav-link" href="{{ url_for('adm') }}">Добавить</a> {% endif %}
                    </li>
                    <li class="nav-item">
                        <!--<a class="nav-link active" aria-current="page" href="{{ url_for('posts.create_post') }}">add post</a>-->
                        {% if current_user.has_role('admin') %}
                        <a class="nav-link active" aria-current="page" href="/admin">Admin</a> {% endif %}
                    </li>
                </ul>

                <!-- Форма поиска-->
                <form class="d-flex search_form" method="GET">

                    <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" name="q" value="{{ request.args.get('q', '') }}">

                    <button class="btn btn-outline-success" type="submit">Найти</button>
                </form>
                <!-- /Форма поиска-->
            </div>
        </div>
    </nav>

    <div class="container">
        <div class="row" style="margin-top:55px;">
            <div class="col-md-12">
                <h2>
                    {% block content_title %}

                    {% endblock %}
                </h2>

                {% block content %}

                {% endblock %}

            </div>
        </div>
    </div>
</main>

<footer class="footer fixed-bottom mt-auto py-3 bg-light">
    <div class="container">
        <span class="text-muted">By AiHead 2021</span>
    </div>
</footer>

</body>

</html>

templates/create.html
{% extends 'base.html' %}

{% block title %}
Create new post
{% endblock %}

{% block content_titletitle %}
New post
{% endblock %}

{% block content %}
<div class="col-md-3">

</div>

<div class="col-md-6">
    <form enctype='multipart/form-data' action="{{ url_for('create_post') }}" method="POST">
        {% for field in form %}
        <div class="form-group">
            {{ field.label(class='control-label')}} {{ field(class='form-control')}}
        </div>
        {% endfor %}
        <button type="submit" class="btn btn-info">Create</button>
    </form>
</div>

<div class="col-md-3"></div>

{% endblock %}

templates/createSlide.html
{% extends 'base.html' %}

{% block title %}
    Создать слайд
{% endblock %}

{% block content_titletitle %}
    Создать слайд
{% endblock %}

{% block content %}
    <div class="col-md-3">

    </div>

    <div class="col-md-6">
        <form enctype = 'multipart/form-data' action="{{ url_for('create_slide') }}" method="post">
            {% for field in form %}
                    <div class="form-group">
                        {{ field.label(class='control-label')}}
                        {{ field(class='form-control')}}
                    </div>
            {% endfor %}
            <button type="submit" class="btn btn-info">Создать</button>
        </form>
    </div>

    <div class="col-md-3"></div>

{% endblock %}

templates/createTag.html
{% extends 'base.html' %}

{% block title %}
    Создать категорию
{% endblock %}

{% block content_titletitle %}
    Создать категорию
{% endblock %}

{% block content %}
    <div class="col-md-3">

    </div>

    <div class="col-md-6">
        <form enctype = 'multipart/form-data' action="{{ url_for('create_tag') }}" method="post">
            {% for field in form %}
                    <div class="form-group">
                        {{ field.label(class='control-label')}}
                        {{ field(class='form-control')}}
                    </div>
            {% endfor %}
            <button type="submit" class="btn btn-info">Создать</button>
        </form>
    </div>

    <div class="col-md-3"></div>

{% endblock %}

templates/index.html
{% extends 'base.html' %}

{% block content %}
<!----------------------------------------------- Слайдер ------------------------------------------------------------>
<div id="carouselExampleControls" class="carousel slide" data-bs-ride="carousel" style="color:black;">
    <div class="carousel-inner">
        {% for s in slides %}
            {% if s.id==1 %}
                <div class="carousel-item active">
                    <img src="../static/image/slider/{{s.image}}" class="d-block w-100" alt="Image">
                    <div class="carousel-caption d-none d-md-block">
                        <h5>{{s.title}}</h5>
                        <p>{{s.body}}</p>
                    </div>
                </div>
            {% else %}
                <div class="carousel-item">
                    <img src="../static/image/slider/{{s.image}}" class="d-block w-100" alt="Image">
                    <div class="carousel-caption d-none d-md-block">
                        <h5>{{s.title}}</h5>
                        <p>{{s.body}}</p>
                    </div>
                </div>
            {% endif %}
        {% endfor %}
    </div>
</div>

<!----------------------------------------- Блок с карточками категорий ----------------------------------------------->
<div class="row indexcat">
    <div class="indexcat__cards">
        {% for c in category %}
            <div class="card" style="width: 17rem; ">
                <img src="../static/image/tagimage/{{c.image}}" class="card-img-top" alt="¯\_(ツ)_/¯">
                <div class="card-body">
                    <h5 class="card-title">{{c.name}}</h5>
                    <a href="{{ url_for('posts.tag_detail', slug=c.slug) }}" class="btn btn-primary">К товарам</a>
                </div>
            </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

templates/where.html
{% extends 'base.html' %}

{% block title %}
    Где купить
{% endblock %}

{% block content_title %}
    <div class="where-title">
        Где купить
    </div>
{% endblock %}

{% block content %}
<div class="container">

    <!--Блок с картой-->
    <div class="col-md-12 map-area">
        <iframe src="https://yandex.ru/map-widget/v1/?um=constructor%3A7ad60f9512b545e6dbc0c1c95e3489c3db5d3bf65d5f60103cb2ecc0ee34af0d&amp;source=constructor"
                width="1080"
                height="400"
                frameborder="0">
        </iframe>
    </div>


    <!--Блок с адресами магазинов-->
    <div class="row row-cols-4 adres-shop-area">

    <div class="col d-flex align-items-start">
      <svg class="bi text-muted flex-shrink-0 me-3" width="1.75em" height="1.75em"></svg>
      <div>
        <h4 class="fw-bold mb-0">Featured title</h4>
        <p>Paragraph of text beneath the heading to explain the heading.</p>
      </div>
    </div>

    <div class="col d-flex align-items-start">
      <svg class="bi text-muted flex-shrink-0 me-3" width="1.75em" height="1.75em"><use xlink:href="#bi-house-fill"></use></svg>
      <div>
        <h4 class="fw-bold mb-0">Featured title</h4>
        <p>Paragraph of text beneath the heading to explain the heading.</p>
      </div>
    </div>

    <div class="col d-flex align-items-start">
      <svg class="bi text-muted flex-shrink-0 me-3" width="1.75em" height="1.75em"><use xlink:href="#calendar3"></use></svg>
      <div>
        <h4 class="fw-bold mb-0">Featured title</h4>
        <p>Paragraph of text beneath the heading to explain the heading.</p>
      </div>
    </div>

<!--    <div class="col d-flex align-items-start">-->
<!--      <svg class="bi text-muted flex-shrink-0 me-3" width="1.75em" height="1.75em"><use xlink:href="#home"></use></svg>-->
<!--      <div>-->
<!--        <h4 class="fw-bold mb-0">Featured title</h4>-->
<!--        <p>Paragraph of text beneath the heading to explain the heading.</p>-->
<!--      </div>-->
<!--    </div>-->

  </div>
</div>
{% endblock %}